### ISSUE TITLE
Public Lambda Layers ARN instead of SAR App

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-lambda-powertools-roadmap#2]
> Original author: @ecolban

**Runtime e.g. Python, Java, all of them.** All of them

**Is your feature request related to a problem? Please describe.**

As described in the [Lambda Powertools Python discussion](https://github.com/awslabs/aws-lambda-powertools-python/discussions/329), Layers are currently available as a Serverless Application Repository (SAR) App and not as a public Lambda Layer ARN.

While this allows customers to selectively deploy the semantic version they're interested in it does require deploying a SAR App before they can use the Lambda Layer.

**Describe the solution you'd like**

Make Lambda Layer ARN publicly available per region. This will make it easier to add Lambda Powertools to existing projects.

Some examples: https://github.com/mthenw/awesome-layers 

**Describe alternatives you've considered**

Building and publishing own Lambda Layer though that adds operational overhead in maintaining.

**Is this something you'd like to contribute if you had guidance?**

**Additional context**

**Comment by stephenbawks** [comment]
Would love to have this as a layer.  Been using Serverless Framework but I see this appears to be only available in eu-west-1.  I am in the US so having layers here as well would be great.

**Comment by heitorlessa** [comment]
Absolutely - one misconception though is that we're using Serverless Application Repository (SAR) Application as a layer, and while its ARN is EU-West-1 it can be deployed anywhere globally.

Once deployed, it'll create a Lambda Layer in the region you deployed, and that's the ARN you can use.

I'll create a sample in the docs on how to do it for Serverless framework, as @am29d continurs to work on the public ARN folks will be able to use directly in Lambda with any framework

**Comment by stephenbawks** [comment]
Ahh gotcha.  Yah sadly I have not used a ton of SAR yet but I guess I will need to check this out.

I am using Serverless Framework for this and being able to add it as a layer would be by far the easy path.

**Comment by stephenbawks** [comment]
I guess maybe a follow up question then now that I think about it.  Since I am using a container for my lambda, are there some install commands where I can pull this in since a layer is not going to work for a container deployment.

**Comment by mwarkentin** [comment]
@stephenbawks doesn't help with your container question, but here's how you can configure this through serverless:

```
resources:
  Transform: AWS::Serverless-2016-10-31
  Resources:
    AwsLambdaPowertoolsPythonLayer:
      Type: AWS::Serverless::Application
      Properties:
        Location:
          ApplicationId: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer
          SemanticVersion: # Add latest version from https://github.com/awslabs/aws-lambda-powertools-python/releases
```

Which can then be used to define the layer:

```
functions:
  main:
    handler: lambda_function.lambda_handler
    layers:
      - !GetAtt AwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn
```
